# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNOneSignal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNOneSignal
  pod 'OneSignal'

  target 'RNOneSignalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
