# Filename (cd.yml) should match the workflow filename in Trusted Publisher setting on npmjs
name: Publish to NPM & Github
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - rel/**

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: read # Required by transitively-called github-release.yml

jobs:
  publish:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.title, 'chore: Release')
    uses: OneSignal/sdk-shared/.github/workflows/publish-npm-github.yml@main
    secrets:
      GH_PUSH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
    with:
      branch: ${{ github.event.pull_request.base.ref }}
